//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDatabaseExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int OperationId { get; set; }
        public string Name { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    }
}
