//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTemplate.Moderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public byte UserId { get; set; }
        public string FrontName { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string TelephoneNumber { get; set; }
        public string IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
