//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTemplate.Moderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public byte UserId { get; set; }
        public byte CountryId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
