//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzanTemplate {
    
    
    public partial class AboutUs {
        
        /// <summary>
        /// UcAboutContactSlider control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcAboutContactSlider UcAboutContactSlider;
        
        /// <summary>
        /// UcIntroText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcIntroText UcIntroText;
        
        /// <summary>
        /// UcOurTeams control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcOurTeams UcOurTeams;
        
        /// <summary>
        /// UcFeatured control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcFeatured UcFeatured;
    }
}
