//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzanTemplate {
    
    
    public partial class Default {
        
        /// <summary>
        /// UcSlider control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcSlider UcSlider;
        
        /// <summary>
        /// UcIntroText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcIntroText UcIntroText;
        
        /// <summary>
        /// UcFeatured control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcFeatured UcFeatured;
        
        /// <summary>
        /// UcExpertises control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcExpertises UcExpertises;
        
        /// <summary>
        /// UcClientChoose control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcClientChoose UcClientChoose;
        
        /// <summary>
        /// UcFreeConsultation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OzanTemplate.UcTemplate.UcFreeConsultation UcFreeConsultation;
    }
}
